"""Initial schema: firms, documents, permits, signals, alerts, auth.

Hand-assembled from the model metadata rather than autogenerated, because the
pgvector extension has to exist before any VECTOR column is created and the HNSW
indexes carry build parameters autogenerate cannot express.

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-07
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Listed per embedding column, so adding a third vector column is a one-line change.
_VECTOR_INDEXES: tuple[tuple[str, str], ...] = (
    ("document_chunks", "embedding"),
    ("firms", "embedding"),
)


def upgrade() -> None:
    # Must precede every VECTOR column below.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # pg_trgm backs trigram similarity on canonical names, which is the cheap
    # pre-filter that keeps entity resolution from fuzzy-scoring all 100+ firms
    # for every permit applicant string.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    op.create_table(
        "digests",
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("markdown", sa.Text(), nullable=False),
        sa.Column("pdf_path", sa.String(length=1000), nullable=True),
        sa.Column("signal_count", sa.Integer(), nullable=False),
        sa.Column("firm_count", sa.Integer(), nullable=False),
        sa.Column("signal_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_digests")),
        sa.UniqueConstraint("period_start", "period_end", name="uq_digest_period"),
    )
    op.create_index("ix_digests_period", "digests", ["period_start", "period_end"], unique=False)
    op.create_index(op.f("ix_digests_period_start"), "digests", ["period_start"], unique=False)
    op.create_table(
        "firms",
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("canonical_name", sa.String(length=300), nullable=False),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("firm_type", sa.String(length=40), nullable=False),
        sa.Column("hq_address", sa.String(length=400), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("county", sa.String(length=120), nullable=True),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("postal_code", sa.String(length=12), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("focus_areas", postgresql.ARRAY(sa.String(length=60)), nullable=False),
        sa.Column("asset_classes", postgresql.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("localities", postgresql.ARRAY(sa.String(length=120)), nullable=False),
        sa.Column("employee_count", sa.Integer(), nullable=True),
        sa.Column("pipeline_project_count", sa.Integer(), nullable=False),
        sa.Column("founded_year", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column("embedding_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lat IS NULL OR (lat BETWEEN -90 AND 90)", name=op.f("ck_firms_lat_range")
        ),
        sa.CheckConstraint(
            "lon IS NULL OR (lon BETWEEN -180 AND 180)", name=op.f("ck_firms_lon_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_firms")),
    )
    op.create_index(
        "ix_firms_asset_classes", "firms", ["asset_classes"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("ix_firms_canonical_name"), "firms", ["canonical_name"], unique=False)
    op.create_index(op.f("ix_firms_city"), "firms", ["city"], unique=False)
    op.create_index(op.f("ix_firms_county"), "firms", ["county"], unique=False)
    op.create_index(op.f("ix_firms_firm_type"), "firms", ["firm_type"], unique=False)
    op.create_index(
        "ix_firms_focus_areas", "firms", ["focus_areas"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("ix_firms_last_activity_at"), "firms", ["last_activity_at"], unique=False)
    op.create_index(
        "ix_firms_localities", "firms", ["localities"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("ix_firms_name"), "firms", ["name"], unique=False)
    op.create_index(op.f("ix_firms_phone"), "firms", ["phone"], unique=False)
    op.create_index(op.f("ix_firms_slug"), "firms", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("company", sa.String(length=200), nullable=True),
        sa.Column("tier", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_tier"), "users", ["tier"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("channel_target", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_fired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fire_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_alerts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index(op.f("ix_alerts_is_active"), "alerts", ["is_active"], unique=False)
    op.create_index(op.f("ix_alerts_user_id"), "alerts", ["user_id"], unique=False)
    op.create_table(
        "api_keys",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("key_hash", sa.String(length=255), nullable=False),
        sa.Column("key_prefix", sa.String(length=20), nullable=False),
        sa.Column("tier", sa.String(length=20), nullable=False),
        sa.Column("rate_limit_per_minute", sa.Integer(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_api_keys_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
    )
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_index(op.f("ix_api_keys_key_prefix"), "api_keys", ["key_prefix"], unique=False)
    op.create_index(op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    op.create_table(
        "sources",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("base_url", sa.String(length=1000), nullable=False),
        sa.Column("firm_id", sa.UUID(), nullable=True),
        sa.Column("locality", sa.String(length=120), nullable=True),
        sa.Column("scrape_task", sa.String(length=40), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cadence_hours", sa.Integer(), nullable=False),
        sa.Column("robots_allowed", sa.Boolean(), nullable=True),
        sa.Column("robots_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_crawled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["firm_id"], ["firms.id"], name=op.f("fk_sources_firm_id_firms"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("base_url", name=op.f("uq_sources_base_url")),
    )
    op.create_index(op.f("ix_sources_firm_id"), "sources", ["firm_id"], unique=False)
    op.create_index(op.f("ix_sources_is_active"), "sources", ["is_active"], unique=False)
    op.create_index(op.f("ix_sources_kind"), "sources", ["kind"], unique=False)
    op.create_index(
        op.f("ix_sources_last_crawled_at"), "sources", ["last_crawled_at"], unique=False
    )
    op.create_index(op.f("ix_sources_locality"), "sources", ["locality"], unique=False)
    op.create_table(
        "trend_windows",
        sa.Column("firm_id", sa.UUID(), nullable=True),
        sa.Column("locality", sa.String(length=120), nullable=True),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("permit_count", sa.Integer(), nullable=False),
        sa.Column("valuation_sum_usd", sa.Float(), nullable=False),
        sa.Column("open_job_count", sa.Integer(), nullable=False),
        sa.Column("news_mention_count", sa.Integer(), nullable=False),
        sa.Column("new_project_count", sa.Integer(), nullable=False),
        sa.Column("asset_class_mix", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("anomaly_score", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["firm_id"],
            ["firms.id"],
            name=op.f("fk_trend_windows_firm_id_firms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trend_windows")),
        sa.UniqueConstraint("firm_id", "locality", "period_start", name="uq_trend_window_period"),
    )
    op.create_index(op.f("ix_trend_windows_firm_id"), "trend_windows", ["firm_id"], unique=False)
    op.create_index(op.f("ix_trend_windows_locality"), "trend_windows", ["locality"], unique=False)
    op.create_index(
        op.f("ix_trend_windows_period_start"), "trend_windows", ["period_start"], unique=False
    )
    op.create_table(
        "raw_documents",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("final_url", sa.String(length=2000), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("content_type", sa.String(length=10), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=600), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("cleaned_text", sa.Text(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extraction_status", sa.String(length=30), nullable=False),
        sa.Column("extraction_error", sa.Text(), nullable=True),
        sa.Column("extraction_attempts", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_raw_documents_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_documents")),
    )
    op.create_index(
        op.f("ix_raw_documents_content_hash"), "raw_documents", ["content_hash"], unique=True
    )
    op.create_index(
        op.f("ix_raw_documents_extraction_status"),
        "raw_documents",
        ["extraction_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_documents_fetched_at"), "raw_documents", ["fetched_at"], unique=False
    )
    op.create_index(
        op.f("ix_raw_documents_published_at"), "raw_documents", ["published_at"], unique=False
    )
    op.create_index(
        op.f("ix_raw_documents_source_id"), "raw_documents", ["source_id"], unique=False
    )
    op.create_index(
        "ix_raw_documents_status_fetched",
        "raw_documents",
        ["extraction_status", "fetched_at"],
        unique=False,
    )
    op.create_table(
        "document_chunks",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("firm_id", sa.UUID(), nullable=True),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["raw_documents.id"],
            name=op.f("fk_document_chunks_document_id_raw_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["firm_id"],
            ["firms.id"],
            name=op.f("fk_document_chunks_firm_id_firms"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_document_chunk_index"),
    )
    op.create_index(
        op.f("ix_document_chunks_document_id"), "document_chunks", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_chunks_firm_id"), "document_chunks", ["firm_id"], unique=False
    )
    op.create_table(
        "entity_candidates",
        sa.Column("mention", sa.String(length=400), nullable=False),
        sa.Column("canonical_mention", sa.String(length=400), nullable=False),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("origin_table", sa.String(length=60), nullable=True),
        sa.Column("origin_id", sa.Uuid(), nullable=True),
        sa.Column("suggestions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("best_score", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("resolved_firm_id", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(length=120), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["resolved_firm_id"],
            ["firms.id"],
            name=op.f("fk_entity_candidates_resolved_firm_id_firms"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["raw_documents.id"],
            name=op.f("fk_entity_candidates_source_document_id_raw_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_candidates")),
        sa.UniqueConstraint("canonical_mention", name="uq_entity_candidate_mention"),
    )
    op.create_index(
        op.f("ix_entity_candidates_canonical_mention"),
        "entity_candidates",
        ["canonical_mention"],
        unique=False,
    )
    op.create_index(
        op.f("ix_entity_candidates_mention"), "entity_candidates", ["mention"], unique=False
    )
    op.create_index(
        op.f("ix_entity_candidates_status"), "entity_candidates", ["status"], unique=False
    )
    op.create_table(
        "firm_aliases",
        sa.Column("firm_id", sa.UUID(), nullable=False),
        sa.Column("alias", sa.String(length=300), nullable=False),
        sa.Column("canonical_alias", sa.String(length=300), nullable=False),
        sa.Column("alias_type", sa.String(length=30), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("resolution_method", sa.String(length=20), nullable=False),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name=op.f("ck_firm_aliases_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["firm_id"],
            ["firms.id"],
            name=op.f("fk_firm_aliases_firm_id_firms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["raw_documents.id"],
            name=op.f("fk_firm_aliases_source_document_id_raw_documents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_firm_aliases")),
        sa.UniqueConstraint("canonical_alias", name="uq_firm_aliases_canonical_alias"),
    )
    op.create_index(op.f("ix_firm_aliases_alias"), "firm_aliases", ["alias"], unique=False)
    op.create_index(
        op.f("ix_firm_aliases_canonical_alias"), "firm_aliases", ["canonical_alias"], unique=False
    )
    op.create_index(op.f("ix_firm_aliases_firm_id"), "firm_aliases", ["firm_id"], unique=False)
    op.create_table(
        "firm_relationships",
        sa.Column("firm_a_id", sa.UUID(), nullable=False),
        sa.Column("firm_b_id", sa.UUID(), nullable=False),
        sa.Column("relation_type", sa.String(length=40), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("evidence_count", sa.Integer(), nullable=False),
        sa.Column("evidence_document_id", sa.UUID(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("first_detected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_detected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "firm_a_id <> firm_b_id", name=op.f("ck_firm_relationships_no_self_relation")
        ),
        sa.CheckConstraint(
            "weight BETWEEN 0 AND 1", name=op.f("ck_firm_relationships_weight_range")
        ),
        sa.ForeignKeyConstraint(
            ["evidence_document_id"],
            ["raw_documents.id"],
            name=op.f("fk_firm_relationships_evidence_document_id_raw_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["firm_a_id"],
            ["firms.id"],
            name=op.f("fk_firm_relationships_firm_a_id_firms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["firm_b_id"],
            ["firms.id"],
            name=op.f("fk_firm_relationships_firm_b_id_firms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_firm_relationships")),
        sa.UniqueConstraint("firm_a_id", "firm_b_id", "relation_type", name="uq_firm_relationship"),
    )
    op.create_index(
        op.f("ix_firm_relationships_firm_a_id"), "firm_relationships", ["firm_a_id"], unique=False
    )
    op.create_index(
        op.f("ix_firm_relationships_firm_b_id"), "firm_relationships", ["firm_b_id"], unique=False
    )
    op.create_index(
        op.f("ix_firm_relationships_relation_type"),
        "firm_relationships",
        ["relation_type"],
        unique=False,
    )
    op.create_table(
        "job_postings",
        sa.Column("firm_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("department", sa.String(length=120), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("employment_type", sa.String(length=60), nullable=True),
        sa.Column("url", sa.String(length=1000), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("posted_date", sa.Date(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["firm_id"],
            ["firms.id"],
            name=op.f("fk_job_postings_firm_id_firms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["raw_documents.id"],
            name=op.f("fk_job_postings_source_document_id_raw_documents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_postings")),
        sa.UniqueConstraint("firm_id", "title", "location", name="uq_job_firm_title_loc"),
    )
    op.create_index(op.f("ix_job_postings_firm_id"), "job_postings", ["firm_id"], unique=False)
    op.create_index(
        "ix_job_postings_firm_open", "job_postings", ["firm_id", "is_open"], unique=False
    )
    op.create_index(
        op.f("ix_job_postings_first_seen_at"), "job_postings", ["first_seen_at"], unique=False
    )
    op.create_index(op.f("ix_job_postings_is_open"), "job_postings", ["is_open"], unique=False)
    op.create_index(op.f("ix_job_postings_location"), "job_postings", ["location"], unique=False)
    op.create_table(
        "people",
        sa.Column("firm_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("canonical_name", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("role_type", sa.String(length=30), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("linkedin_url", sa.String(length=500), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["firm_id"], ["firms.id"], name=op.f("fk_people_firm_id_firms"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["raw_documents.id"],
            name=op.f("fk_people_source_document_id_raw_documents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_people")),
        sa.UniqueConstraint("firm_id", "canonical_name", name="uq_person_firm_name"),
    )
    op.create_index(op.f("ix_people_canonical_name"), "people", ["canonical_name"], unique=False)
    op.create_index("ix_people_firm_current", "people", ["firm_id", "is_current"], unique=False)
    op.create_index(op.f("ix_people_firm_id"), "people", ["firm_id"], unique=False)
    op.create_index(op.f("ix_people_is_current"), "people", ["is_current"], unique=False)
    op.create_index(op.f("ix_people_name"), "people", ["name"], unique=False)
    op.create_index(op.f("ix_people_role_type"), "people", ["role_type"], unique=False)
    op.create_table(
        "property_projects",
        sa.Column("firm_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=400), nullable=False),
        sa.Column("project_type", sa.String(length=40), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("locality", sa.String(length=120), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("parcel_ids", postgresql.ARRAY(sa.String(length=60)), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("acreage", sa.Float(), nullable=True),
        sa.Column("unit_count", sa.Integer(), nullable=True),
        sa.Column("square_feet", sa.Integer(), nullable=True),
        sa.Column("est_value_usd", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("announced_date", sa.Date(), nullable=True),
        sa.Column("expected_completion", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "lat IS NULL OR (lat BETWEEN -90 AND 90)", name=op.f("ck_property_projects_lat_range")
        ),
        sa.CheckConstraint(
            "lon IS NULL OR (lon BETWEEN -180 AND 180)", name=op.f("ck_property_projects_lon_range")
        ),
        sa.ForeignKeyConstraint(
            ["firm_id"],
            ["firms.id"],
            name=op.f("fk_property_projects_firm_id_firms"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["raw_documents.id"],
            name=op.f("fk_property_projects_source_document_id_raw_documents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_property_projects")),
    )
    op.create_index(
        op.f("ix_property_projects_announced_date"),
        "property_projects",
        ["announced_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_property_projects_firm_id"), "property_projects", ["firm_id"], unique=False
    )
    op.create_index("ix_property_projects_geo", "property_projects", ["lat", "lon"], unique=False)
    op.create_index(
        op.f("ix_property_projects_locality"), "property_projects", ["locality"], unique=False
    )
    op.create_index(op.f("ix_property_projects_name"), "property_projects", ["name"], unique=False)
    op.create_index(
        "ix_property_projects_parcel_ids",
        "property_projects",
        ["parcel_ids"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_property_projects_project_type"),
        "property_projects",
        ["project_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_property_projects_status"), "property_projects", ["status"], unique=False
    )
    op.create_table(
        "signals",
        sa.Column("firm_id", sa.UUID(), nullable=True),
        sa.Column("signal_type", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=400), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("locality", sa.String(length=120), nullable=True),
        sa.Column("asset_class", sa.String(length=40), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_derived", sa.Boolean(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("score BETWEEN 0 AND 1", name=op.f("ck_signals_score_range")),
        sa.ForeignKeyConstraint(
            ["firm_id"], ["firms.id"], name=op.f("fk_signals_firm_id_firms"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["raw_documents.id"],
            name=op.f("fk_signals_source_document_id_raw_documents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signals")),
    )
    op.create_index(op.f("ix_signals_asset_class"), "signals", ["asset_class"], unique=False)
    op.create_index(op.f("ix_signals_dedupe_key"), "signals", ["dedupe_key"], unique=True)
    op.create_index(op.f("ix_signals_detected_at"), "signals", ["detected_at"], unique=False)
    op.create_index("ix_signals_detected_score", "signals", ["detected_at", "score"], unique=False)
    op.create_index(op.f("ix_signals_firm_id"), "signals", ["firm_id"], unique=False)
    op.create_index("ix_signals_firm_occurred", "signals", ["firm_id", "occurred_at"], unique=False)
    op.create_index(op.f("ix_signals_is_derived"), "signals", ["is_derived"], unique=False)
    op.create_index(op.f("ix_signals_locality"), "signals", ["locality"], unique=False)
    op.create_index(op.f("ix_signals_occurred_at"), "signals", ["occurred_at"], unique=False)
    op.create_index(op.f("ix_signals_score"), "signals", ["score"], unique=False)
    op.create_index(op.f("ix_signals_signal_type"), "signals", ["signal_type"], unique=False)
    op.create_index(
        "ix_signals_type_occurred", "signals", ["signal_type", "occurred_at"], unique=False
    )
    op.create_table(
        "alert_deliveries",
        sa.Column("alert_id", sa.UUID(), nullable=False),
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alerts.id"],
            name=op.f("fk_alert_deliveries_alert_id_alerts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
            name=op.f("fk_alert_deliveries_signal_id_signals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_deliveries")),
        sa.UniqueConstraint("alert_id", "signal_id", name="uq_alert_delivery"),
    )
    op.create_index(
        op.f("ix_alert_deliveries_alert_id"), "alert_deliveries", ["alert_id"], unique=False
    )
    op.create_index(
        op.f("ix_alert_deliveries_signal_id"), "alert_deliveries", ["signal_id"], unique=False
    )
    op.create_index(
        op.f("ix_alert_deliveries_status"), "alert_deliveries", ["status"], unique=False
    )
    op.create_table(
        "permits",
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("firm_id", sa.UUID(), nullable=True),
        sa.Column("locality", sa.String(length=120), nullable=False),
        sa.Column("permit_number", sa.String(length=80), nullable=False),
        sa.Column("permit_type", sa.String(length=120), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("applicant_name_raw", sa.String(length=400), nullable=True),
        sa.Column("owner_name_raw", sa.String(length=400), nullable=True),
        sa.Column("contractor_name_raw", sa.String(length=400), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("parcel_id", sa.String(length=60), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("valuation_usd", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("filed_date", sa.Date(), nullable=True),
        sa.Column("issued_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=60), nullable=True),
        sa.Column("resolution_method", sa.String(length=20), nullable=True),
        sa.Column("resolution_confidence", sa.Float(), nullable=True),
        sa.Column("source_document_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["firm_id"], ["firms.id"], name=op.f("fk_permits_firm_id_firms"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["property_projects.id"],
            name=op.f("fk_permits_project_id_property_projects"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["raw_documents.id"],
            name=op.f("fk_permits_source_document_id_raw_documents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permits")),
        sa.UniqueConstraint("locality", "permit_number", name="uq_permit_locality_number"),
    )
    op.create_index(
        op.f("ix_permits_applicant_name_raw"), "permits", ["applicant_name_raw"], unique=False
    )
    op.create_index(op.f("ix_permits_filed_date"), "permits", ["filed_date"], unique=False)
    op.create_index("ix_permits_firm_filed", "permits", ["firm_id", "filed_date"], unique=False)
    op.create_index(op.f("ix_permits_firm_id"), "permits", ["firm_id"], unique=False)
    op.create_index(op.f("ix_permits_issued_date"), "permits", ["issued_date"], unique=False)
    op.create_index(op.f("ix_permits_locality"), "permits", ["locality"], unique=False)
    op.create_index(
        "ix_permits_locality_filed", "permits", ["locality", "filed_date"], unique=False
    )
    op.create_index(op.f("ix_permits_parcel_id"), "permits", ["parcel_id"], unique=False)
    op.create_index(op.f("ix_permits_permit_number"), "permits", ["permit_number"], unique=False)
    op.create_index(op.f("ix_permits_permit_type"), "permits", ["permit_type"], unique=False)
    op.create_index(op.f("ix_permits_project_id"), "permits", ["project_id"], unique=False)

    # Trigram indexes for the entity-resolution pre-filter.
    op.execute(
        "CREATE INDEX ix_firms_canonical_name_trgm ON firms USING gin (canonical_name gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_firm_aliases_canonical_trgm "
        "ON firm_aliases USING gin (canonical_alias gin_trgm_ops)"
    )

    # HNSW rather than IVFFlat: IVFFlat needs a populated table to build useful
    # centroids, and this schema starts empty. HNSW is correct from row zero and
    # degrades gracefully as the corpus grows.
    for table, column in _VECTOR_INDEXES:
        op.execute(
            f"CREATE INDEX ix_{table}_{column}_hnsw ON {table} "
            f"USING hnsw ({column} vector_cosine_ops) "
            "WITH (m = 16, ef_construction = 64)"
        )


def downgrade() -> None:
    for table, column in _VECTOR_INDEXES:
        op.execute(f"DROP INDEX IF EXISTS ix_{table}_{column}_hnsw")
    op.execute("DROP INDEX IF EXISTS ix_firm_aliases_canonical_trgm")
    op.execute("DROP INDEX IF EXISTS ix_firms_canonical_name_trgm")

    op.drop_index(op.f("ix_permits_applicant_name_raw"), table_name="permits")
    op.drop_index(op.f("ix_permits_filed_date"), table_name="permits")
    op.drop_index("ix_permits_firm_filed", table_name="permits")
    op.drop_index(op.f("ix_permits_firm_id"), table_name="permits")
    op.drop_index(op.f("ix_permits_issued_date"), table_name="permits")
    op.drop_index(op.f("ix_permits_locality"), table_name="permits")
    op.drop_index("ix_permits_locality_filed", table_name="permits")
    op.drop_index(op.f("ix_permits_parcel_id"), table_name="permits")
    op.drop_index(op.f("ix_permits_permit_number"), table_name="permits")
    op.drop_index(op.f("ix_permits_permit_type"), table_name="permits")
    op.drop_index(op.f("ix_permits_project_id"), table_name="permits")
    op.drop_table("permits")
    op.drop_index(op.f("ix_alert_deliveries_alert_id"), table_name="alert_deliveries")
    op.drop_index(op.f("ix_alert_deliveries_signal_id"), table_name="alert_deliveries")
    op.drop_index(op.f("ix_alert_deliveries_status"), table_name="alert_deliveries")
    op.drop_table("alert_deliveries")
    op.drop_index(op.f("ix_signals_asset_class"), table_name="signals")
    op.drop_index(op.f("ix_signals_dedupe_key"), table_name="signals")
    op.drop_index(op.f("ix_signals_detected_at"), table_name="signals")
    op.drop_index("ix_signals_detected_score", table_name="signals")
    op.drop_index(op.f("ix_signals_firm_id"), table_name="signals")
    op.drop_index("ix_signals_firm_occurred", table_name="signals")
    op.drop_index(op.f("ix_signals_is_derived"), table_name="signals")
    op.drop_index(op.f("ix_signals_locality"), table_name="signals")
    op.drop_index(op.f("ix_signals_occurred_at"), table_name="signals")
    op.drop_index(op.f("ix_signals_score"), table_name="signals")
    op.drop_index(op.f("ix_signals_signal_type"), table_name="signals")
    op.drop_index("ix_signals_type_occurred", table_name="signals")
    op.drop_table("signals")
    op.drop_index(op.f("ix_property_projects_announced_date"), table_name="property_projects")
    op.drop_index(op.f("ix_property_projects_firm_id"), table_name="property_projects")
    op.drop_index("ix_property_projects_geo", table_name="property_projects")
    op.drop_index(op.f("ix_property_projects_locality"), table_name="property_projects")
    op.drop_index(op.f("ix_property_projects_name"), table_name="property_projects")
    op.drop_index(
        "ix_property_projects_parcel_ids", table_name="property_projects", postgresql_using="gin"
    )
    op.drop_index(op.f("ix_property_projects_project_type"), table_name="property_projects")
    op.drop_index(op.f("ix_property_projects_status"), table_name="property_projects")
    op.drop_table("property_projects")
    op.drop_index(op.f("ix_people_canonical_name"), table_name="people")
    op.drop_index("ix_people_firm_current", table_name="people")
    op.drop_index(op.f("ix_people_firm_id"), table_name="people")
    op.drop_index(op.f("ix_people_is_current"), table_name="people")
    op.drop_index(op.f("ix_people_name"), table_name="people")
    op.drop_index(op.f("ix_people_role_type"), table_name="people")
    op.drop_table("people")
    op.drop_index(op.f("ix_job_postings_firm_id"), table_name="job_postings")
    op.drop_index("ix_job_postings_firm_open", table_name="job_postings")
    op.drop_index(op.f("ix_job_postings_first_seen_at"), table_name="job_postings")
    op.drop_index(op.f("ix_job_postings_is_open"), table_name="job_postings")
    op.drop_index(op.f("ix_job_postings_location"), table_name="job_postings")
    op.drop_table("job_postings")
    op.drop_index(op.f("ix_firm_relationships_firm_a_id"), table_name="firm_relationships")
    op.drop_index(op.f("ix_firm_relationships_firm_b_id"), table_name="firm_relationships")
    op.drop_index(op.f("ix_firm_relationships_relation_type"), table_name="firm_relationships")
    op.drop_table("firm_relationships")
    op.drop_index(op.f("ix_firm_aliases_alias"), table_name="firm_aliases")
    op.drop_index(op.f("ix_firm_aliases_canonical_alias"), table_name="firm_aliases")
    op.drop_index(op.f("ix_firm_aliases_firm_id"), table_name="firm_aliases")
    op.drop_table("firm_aliases")
    op.drop_index(op.f("ix_entity_candidates_canonical_mention"), table_name="entity_candidates")
    op.drop_index(op.f("ix_entity_candidates_mention"), table_name="entity_candidates")
    op.drop_index(op.f("ix_entity_candidates_status"), table_name="entity_candidates")
    op.drop_table("entity_candidates")
    op.drop_index(op.f("ix_document_chunks_document_id"), table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_firm_id"), table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index(op.f("ix_raw_documents_content_hash"), table_name="raw_documents")
    op.drop_index(op.f("ix_raw_documents_extraction_status"), table_name="raw_documents")
    op.drop_index(op.f("ix_raw_documents_fetched_at"), table_name="raw_documents")
    op.drop_index(op.f("ix_raw_documents_published_at"), table_name="raw_documents")
    op.drop_index(op.f("ix_raw_documents_source_id"), table_name="raw_documents")
    op.drop_index("ix_raw_documents_status_fetched", table_name="raw_documents")
    op.drop_table("raw_documents")
    op.drop_index(op.f("ix_trend_windows_firm_id"), table_name="trend_windows")
    op.drop_index(op.f("ix_trend_windows_locality"), table_name="trend_windows")
    op.drop_index(op.f("ix_trend_windows_period_start"), table_name="trend_windows")
    op.drop_table("trend_windows")
    op.drop_index(op.f("ix_sources_firm_id"), table_name="sources")
    op.drop_index(op.f("ix_sources_is_active"), table_name="sources")
    op.drop_index(op.f("ix_sources_kind"), table_name="sources")
    op.drop_index(op.f("ix_sources_last_crawled_at"), table_name="sources")
    op.drop_index(op.f("ix_sources_locality"), table_name="sources")
    op.drop_table("sources")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_key_prefix"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_user_id"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_alerts_is_active"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_user_id"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_tier"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_firms_asset_classes", table_name="firms", postgresql_using="gin")
    op.drop_index(op.f("ix_firms_canonical_name"), table_name="firms")
    op.drop_index(op.f("ix_firms_city"), table_name="firms")
    op.drop_index(op.f("ix_firms_county"), table_name="firms")
    op.drop_index(op.f("ix_firms_firm_type"), table_name="firms")
    op.drop_index("ix_firms_focus_areas", table_name="firms", postgresql_using="gin")
    op.drop_index(op.f("ix_firms_last_activity_at"), table_name="firms")
    op.drop_index("ix_firms_localities", table_name="firms", postgresql_using="gin")
    op.drop_index(op.f("ix_firms_name"), table_name="firms")
    op.drop_index(op.f("ix_firms_phone"), table_name="firms")
    op.drop_index(op.f("ix_firms_slug"), table_name="firms")
    op.drop_table("firms")
    op.drop_index("ix_digests_period", table_name="digests")
    op.drop_index(op.f("ix_digests_period_start"), table_name="digests")
    op.drop_table("digests")

    # The extensions are deliberately left installed: other schemas in the same
    # database may depend on them, and a DROP EXTENSION is not safely reversible.
